### ISSUE TITLE
Springboot isn't running

### ISSUE THREAD

**Issue by AviKo1** [raghavendra-hegde/postman-workflow-demo#1]
Hello, great article on medium btw. 
I was trying to run the project without any modifications, got below error. Please let me know if you have come across this error, and how to fix it.

 ------------------ ERROR ---------------------
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Hibernate: drop table if exists employee cascade
Feb 28, 2021 6:52:55 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Tomcat]
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1159)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)

-------------------- END OF ERROR -----------

**Comment by AviKo1** [comment]
I have tried installing hibernate and jaxb-api dependencies, but it didn't work.

**Comment by raghavendra-hegde** [comment]
I am not facing this issue, if you say u did not make any changes to the code then probably try changing the username and password in the application.properties file as you have set for the postgress.
